# Generated by Django 6.0.1 on 2026-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='category',
            new_name='equipment_name',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='max_temperature',
            new_name='flowrate',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pressure_rating',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='material',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='temperature',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
